#!/bin/bash

. common.rc

case $1 in
  start)
    start idea /home/devel/ide/idea/bin/idea.sh
    ;;
  stop)
    stop idea
    ;;
  remove)
    remove idea
    ;;
  status)
    status idea
    ;;
  "")
    start idea /home/devel/ide/idea/bin/idea.sh
    ;;
  *)
    usage
    ;;
esac
