#!/bin/bash

script_dir=$(dirname $0)

homedir=/home/ubuntu

if [ -f "$script_dir/env.sh" ]; then
    . "$script_dir/env.sh"
fi

common_args="--add-host host.docker.internal:host-gateway \
            -v /tmp/.X11-unix:/tmp/.X11-unix -v /mnt/wslg:/mnt/wslg \
            -v /run/user/1000:/run/user/1000 -v /etc/localtime:/etc/localtime:ro \
            -e DISPLAY -e WAYLAND_DISPLAY -e XDG_RUNTIME_DIR -e PULSE_SERVER \
            -e HTTPS_PROXY -e HTTP_PROXY -e NO_PROXY \
            -v $HOME/.config:$homedir/.config -v $HOME/.cache:$homedir/.cache \
            -v $HOME/.local:$homedir/.local -v $HOME/.ssh:$homedir/.ssh \
            -v $HOME/.java:$homedir/.java -v $HOME/.m2:$homedir/.m2 \
            -v $HOME/.p2:$homedir/.p2 -v $HOME/.eclipse:$homedir/.eclipse \
            -v $HOME/.jbr:$homedir/.jbr  -v $HOME/.cloudflared:$homedir/.cloudflared \
            -v $HOME/source:$homedir/source -v $HOME/java:$homedir/java \
            -v $HOME/workspace:$homedir/workspace -v $HOME/.gitconfig:$homedir/.gitconfig \
            $DOCKER_EXTRA_ARGS"

ensuredir() {
    if [ ! -d "$HOME/.config" ]; then
        mkdir $HOME/.config
    fi
    if [ ! -d "$HOME/.cache" ]; then
        mkdir $HOME/.cache
    fi
    if [ ! -d "$HOME/.ssh" ]; then
        mkdir $HOME/.ssh
    fi
    if [ ! -d "$HOME/.local" ]; then
        mkdir $HOME/.local
    fi
    if [ ! -d "$HOME/.java" ]; then
        mkdir $HOME/.java
    fi
    if [ ! -d "$HOME/.m2" ]; then
        mkdir $HOME/.m2
    fi
    if [ ! -d "$HOME/.p2" ]; then
        mkdir $HOME/.p2
    fi
    if [ ! -d "$HOME/.jbr" ]; then
        mkdir $HOME/.jbr
    fi
    if [ ! -d "$HOME/.eclipse" ]; then
        mkdir $HOME/.eclipse
    fi
    if [ ! -d "$HOME/.cloudflared" ]; then
        mkdir $HOME/.cloudflared
    fi
    if [ ! -f "$HOME/.gitconfig" ]; then
        touch $HOME/.gitconfig
    fi
}

start() {
    name=$1
    cmd=$2

    state=$(docker ps -af name=$name --format json|jq -r '.State')

    if [ "$state" == "exited" ]; then
        echo "$name starting ..."
        docker start $name
        echo 'done'
        exit 0
    elif [ "$state" == "running" ]; then
        echo "an $name instance is running..."
        exit 0
    fi

    ensuredir
    echo "$name starting ..."
    docker run $common_args --name $name -d jianshao/java-dev:21 $cmd
    echo 'done'
}

cmd() {
    name=$1
    cmd=$2

    state=$(docker ps -af name=$name --format json|jq -r '.State')

    if [ "$state" == "exited" ]; then
        echo "$name removing ..."
        docker rm $name
        echo 'done'
    elif [ "$state" == "running" ]; then
        echo "an $name instance is running..."
        exit 0
    fi

    ensuredir
    docker run $common_args --name $name --rm -it jianshao/java-dev:21 $cmd
}

stop() {
    name=$1
    docker stop $name
}

remove() {
    name=$1
    docker rm $name
}

shell() {
    name=$1
    docker exec -it $name bash
}

status() {
    name=$1
    docker ps -af name=$name --format json | jq -r '.State'
}

logs() {
    name=$1
    docker logs -f $name
}

usage () {
  echo "Usage: `basename $0` [start|stop|status]"
  return 2
}
