#!/bin/bash

. common

case $1 in
  start)
    start eclipse /home/devel/java/eclipse/eclipse
    ;;
  stop)
    stop eclipse
    ;;
  remove)
    remove eclipse
    ;;
  status)
    status eclipse
    ;;
  "")
    start eclipse /home/devel/java/eclipse/eclipse
    ;;
  *)
    usage
    ;;
esac
