#!/bin/bash

. common

case $1 in
  start)
    start idea $homedir/java/idea/bin/idea
    ;;
  stop)
    stop idea
    ;;
  remove)
    remove idea
    ;;
  shell)
    shell idea
    ;;
  status)
    status idea
    ;;
  logs)
    logs idea
    ;;
  "")
    start idea $homedir/java/idea/bin/idea
    ;;
  *)
    usage
    ;;
esac
